- name: Copy k8s file to master node
  hosts: masters
  become: true
  tasks:
    - name: Copy k8s file to master node
      copy:
        src: "{{ playbook_dir }}/../../k8s-multi-stage.yml"
        dest: "{{ home_dir }}"
        remote_src: false 

    - name: Remove existing k8s cluster
      command: "kubectl delete -f {{ home_dir }}/k8s-multi-stage.yml"
      ignore_errors: true
    
    - name: Deploy k8s cluster
      command: "kubectl apply -f {{ home_dir }}/k8s-multi-stage.yml"
