- name: Copy k8s file to master node
  hosts: masters
  become: true
  tasks:
    - name: Copy k8s file to master node
      copy:
        src: ../../k8s-multi-stage.yml  
        dest: "{{ home_dir }}"
        remote_src: yes 
    
    - name: Deploy k8s cluster
      command: "kubectl apply -f {{ home_dir }}/k8s-multi-stage.yml"
