- name: Setup prometheus
  hosts: masters
  become: true
  tasks:
    - name: Add prometheus repository
      command: "helm repo add prometheus-community https://prometheus-community.github.io/helm-charts"
    
    - name: Update repository
      command: "helm repo update"

    - name: Add prometheus repo
      command: "helm install prometheus prometheus-community/prometheus"
    
    - name: Expose prometheus service
      command: "kubectl expose service prometheus-server --type=NodePort --target-port=9090 --name=prometheus-server-ext"

    
    
    
